"""
AI service for content generation using Gemini API
"""
import google.generativeai as genai
from typing import List, Dict, Optional
from config import GEMINI_API_KEY


class AIService:
    """Service for AI-powered content generation"""
    
    def __init__(self):
        """Initialize the AI service"""
        if GEMINI_API_KEY:
            genai.configure(api_key=GEMINI_API_KEY)
            self.model = genai.GenerativeModel('gemini-2.5-flash')
            self.enabled = True
        else:
            self.model = None
            self.enabled = False
    
    def suggest_outline(self, topic: str, doc_type: str) -> List[str]:
        """
        Suggest an outline for a document based on topic
        
        Args:
            topic: The document topic
            doc_type: Either "docx" or "pptx"
        
        Returns:
            List of section titles or slide titles
        """
        if not self.enabled:
            # Return placeholder outline if API key not configured
            if doc_type == "docx":
                return [
                    "Introduction",
                    "Background",
                    "Main Content",
                    "Analysis",
                    "Conclusion"
                ]
            else:
                return [
                    "Title Slide",
                    "Introduction",
                    "Key Points",
                    "Analysis",
                    "Conclusion"
                ]
        
        try:
            if doc_type == "docx":
                prompt = f"""Generate a structured outline for a professional document about: {topic}

Provide 5-7 section titles that would make a comprehensive document.
Return only the section titles, one per line, without numbering or bullets."""
            else:
                prompt = f"""Generate a structured outline for a professional PowerPoint presentation about: {topic}

Provide 5-8 slide titles that would make a comprehensive presentation.
Return only the slide titles, one per line, without numbering or bullets."""
            
            response = self.model.generate_content(prompt)
            sections = [line.strip() for line in response.text.strip().split('\n') if line.strip()]
            return sections
        except Exception as e:
            print(f"Error generating outline: {e}")
            # Return default outline on error
            if doc_type == "docx":
                return [
                    "Introduction",
                    "Background",
                    "Main Content",
                    "Analysis",
                    "Conclusion"
                ]
            else:
                return [
                    "Title Slide",
                    "Introduction",
                    "Key Points",
                    "Analysis",
                    "Conclusion"
                ]
    
    def generate_section_content(
        self, 
        topic: str, 
        section_title: str, 
        doc_type: str,
        context: Optional[str] = None
    ) -> str:
        """
        Generate content for a specific section or slide
        
        Args:
            topic: The overall document topic
            section_title: The title of this section/slide
            doc_type: Either "docx" or "pptx"
            context: Optional context from previous sections
        
        Returns:
            Generated content as string
        """
        if not self.enabled:
            return f"[Placeholder content for '{section_title}']\n\nThis is sample content that would be generated by the AI. Configure your GEMINI_API_KEY in the .env file to enable actual AI generation.\n\nTopic: {topic}"
        
        try:
            if doc_type == "docx":
                prompt = f"""Write detailed content for a document section.

Document Topic: {topic}
Section Title: {section_title}
{f'Previous Context: {context}' if context else ''}

Write 2-3 paragraphs of professional, informative content for this section. Make it detailed and relevant to the topic.
IMPORTANT: Do not include the section title in the output. Do not use markdown bolding (**) or headings (##)."""
            else:
                prompt = f"""Write content for a PowerPoint slide.

Presentation Topic: {topic}
Slide Title: {section_title}
{f'Previous Context: {context}' if context else ''}

Provide 3-5 bullet points of concise, impactful content for this slide. Each bullet should be clear and professional.
IMPORTANT: Do not include the slide title in the output. Do not use markdown bolding (**) or headings (##). Use standard bullet points (• or -)."""
            
            response = self.model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            print(f"Error generating content: {e}")
            return f"Error generating content: {str(e)}"
    
    def refine_content(
        self, 
        original_content: str, 
        refinement_prompt: str,
        section_title: str
    ) -> str:
        """
        Refine existing content based on user feedback
        
        Args:
            original_content: The current content
            refinement_prompt: User's refinement instructions
            section_title: The section/slide title
        
        Returns:
            Refined content
        """
        if not self.enabled:
            return f"{original_content}\n\n[Refinement applied: {refinement_prompt}]"
        
        try:
            prompt = f"""Refine the following content based on the user's instructions.

Section Title: {section_title}
Current Content:
{original_content}

User Instructions: {refinement_prompt}

Provide the refined content, maintaining the same format and style but incorporating the requested changes.
IMPORTANT: Do not include the section title in the output. Do not use markdown bolding (**) or headings (##)."""
            
            response = self.model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            print(f"Error refining content: {e}")
            return original_content


# Global AI service instance
ai_service = AIService()
